---
name: MCVS-PR-validation-action
"on":
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_call:
jobs:
  MCVS-PR-validation-action:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: schubergphilis/mcvs-pr-validation-action@v0.2.0
